#!/bin/bash

while :
do
	result=`curl -m 30 http://c9.etf.unsa.ba/zamger/ping.php`
	timenow=`date`

	if [ "$result" != "ERROR" ]
	then
		echo \($timenow\) Notok - restarting
		ps ax | grep fpm | grep -v grep | grep master | cut -c 1-5 | xargs kill
		sleep 3
		php5-fpm
	else
		echo \($timenow\) Ok
	fi
	sleep 30
done
