#!/bin/bash

dtime=`date +%s`

local=(`/usr/local/webide/bin/webidectl server-stats`)
nfs=(`ssh 172.16.20.91 /usr/local/webide/bin/webidectl server-stats`)
prim=(`ssh 172.16.20.21 /usr/local/webide/bin/webidectl server-stats`)
second=(`ssh 172.16.20.22 /usr/local/webide/bin/webidectl server-stats`)

let "z = ${local[3]} + ${prim[3]} + ${second[3]}"

echo $dtime ${local[2]} $z >> /usr/local/webide/user_stats.log
echo $dtime ${local[0]} ${nfs[0]} ${prim[0]} ${second[0]} >> /usr/local/webide/load_stats.log
echo $dtime ${local[1]} ${nfs[1]} ${prim[1]} ${second[1]} >> /usr/local/webide/mem_stats.log
