{
  "script": [
    "set -e",
    "if [ \"$debug\" == true ]; then ",
        "/usr/local/webide/runners/c_runner.sh \"$file_path\" \"$file\" DEBUGPORT",
    "else",
        "/usr/local/webide/runners/c_runner.sh \"$file_path\" \"$file\"",
    "fi"
  ],
    "info": "Running $file_path/$file_name",
    "env": {},
    "selector": "^.*\\.c$",
    "debugger": "gdb",
    "debugport" : DEBUGPORT,
    "executable": "$file_path/.runme",
    "maxdepth": 50
}
