<p><b>27.10.2016 11:15</b> Otklonjen je bug u pluginu za formatiranje koda (astyle) zbog koje je ovaj plugin potpuno brisao kod. Molimo vas još jednom da ovakve bugove prijavljujete! Njihova popravka traje maksimalno 10 minuta.</p>
<p><b>17.10.2016 20:10</b> Server je danas bio nedostupan od 16:00 iz nepoznatih razloga, restart je riješio problem. Ako uočite da je server nedostupan slobodno kontaktirajte administratora putem maila vljubovic@etf.unsa.ba.</p>
<p><b>9.10.2016 19:00</b> Povodom početka nastave u novoj ak. godini, folderi OR i TP su preimenovani u OR2015 i TP2015. Predlažemo ponovcima da tutorijale rade ispočetka radi vježbe.</p>
<p><b>25.8.2016 13:45</b> Vježbajte ispise iz ORa: <a href="http://c9.etf.unsa.ba/or_game/" target="_blank">http://c9.etf.unsa.ba/or_game/</a> Za korištenje ovog servisa morate biti prijavljeni na c9.</p>
<p><b>17.8.2016 11:40</b> Nadamo se da vam se sviđa novi Dashboard :)</p>
<p><b>25.4.2016 09:30</b> C9 je neočekivano postao nedostupan oko 22h sinoć zbog neuspjelog restarta. Pošto je server fizički nedostupan neradnim danom, normalan rad je nastavljen tek jutros u 9:30. Izvinjavamo se zbog neugodnosti.</p>
<p><b>17.3.2016 07:40</b> Pojedini korisnici su prijavili probleme sa brisanjem dijela koda otkucanog za vrijeme dok traje snimanje (Saving). Pošto ovakvih problema nije ranije bilo, jedino što ih je moglo izazvati je neki bug u collab modu, pa će zbog toga ovaj mod do daljnjeg biti isključen.</p>
<p><b>10.3.2016 22:50</b> Korisnici sada mogu vidjeti <b>anotacije</b> u kodu za poruke kompajlera, debuggera i profilera (valgrind - tj. greške tipa curenje memorije, izlazak van opsega niza i pristup neinicijalizovanim vrijednostima će biti prikazane u trenutku kada se dogode), te je popravljen prikaz popup prozora kod kompajlerskih grešaka koji nakon prelaska na C++ povremeno nije radio.<br>
<img src="/static/images/content/errmsg1.png" width="767" height="506"> <img src="/static/images/content/errmsg2.png" width="542" height="587"> <img src="/static/images/content/errmsg3.png"> <img src="/static/images/content/errmsg4.png"></p>
<p><b>9.3.2016 23:30</b> Nova funkcionalnost <b>collab mode</b> omogućuje tutorima da otvore ekran studenta i pomognu u vezi zadatka direktno u prozoru. Oboje kolaborativno radi na kodu (vide se dva kursora) a sa desne strane se može naći kartica Collaborate u kojoj je chat prozor. Za sada oba korisnika imaju ime "You" što će u budućnosti također biti ispravljeno.</p>
<p><b>8.3.2016 23:30</b> Na zahtjev mnogobrojnih korisnika pokušali smo urediti da Debug način rada bude isključen po defaultu, mada izgleda da na nekim browserima je opet uključen. Molimo korisnika koji i dalje imaju ovakav problem da se jave radi debugginga.</p>
<p><b>8.3.2016 17:30</b> U proteklih 3-4 sata plugin Zadaci imao je grešku zbog koje je urađene zadatke zamjenjivao default main datotekom (hello world). Ova greška je popravljena a studenti koji su greškom obrisali zadatke mogu se javiti kako bi im bila vraćena prethodna verzija.</p>
<p><b>8.3.2016 2:50</b> Niz unaprjeđenja u administrativnom panelu omogućuje tutorima da definišu zadatke i dodaju/mijenjaju autotestove po želji bez kontaktiranja administratora.</p>
<p><b>6.3.2016 23:30</b> Uočili smo da povremeno dolazi do zastoja u radu naslovne stranice (prozora za prijavu) praćenog porukom 502 Bad Gateway i neobjašnjivog porasta opterećenja na serveru. Pokušavamo otkriti uzrok problema, čini se da je nešto vezano za rad PHPa. Ovaj problem će u skorije vrijeme biti otklonjen.</p>
<p><b>3.3.2016 13:30</b> Jedna od novih funkcionalnosti je i procesiranje tzv. <a href="https://en.wikipedia.org/wiki/Core_dump" style="color:cyan">core dump</a> datoteka (core, .core, .valgrind.core itd.) koje omogućuju da se ustanovi zašto se neki program krahirao. No ove datoteke koje su inače povelike nisu brisane tako da je nestalo prostora na disku servera. Usljed ovoga je server bio povremeno nedostupan jutros. Nažalost backup procedura koju koristimo nije predvidjela ovu mogućnost tako da su za nekih 10ak korisnika potpuno obrisani radni folderi ali i njihov backup tako da se ne može vratiti. Ovim korisnicima se Izvinjavamo. Srećom semestar je tek počeo tako da nije izgubljeno puno.</p>
<p><b>26.2.2016 15:30</b> U letu je popravljen određeni broj problema sa novom verzijom. Ukinuta je nebitna poruka &quot;Debugger connection error null&quot; koja se ispisivala svaki put ako se program odmah završi bez grešaka. Debugger bi sada trebao po defaultu biti isključen ali izgleda da c9 pamti vašu posljednju postavku pa za svaki slučaj isključite debugger ako ga ne koristite. Popravljeno je automatsko brisanje core-dump datoteka koje su zatrpavale diskovni prostor na serveru i usporavale rad.</p>
<p><b>26.2.2016 9:30</b> Sinoć od 20:00 do jutros oko 3:00 bilo je otežano pristupanje serveru jer je veliki broj korisnika poletilo da pogleda novu verziju a nisu napravili logout, tako da je dosegnut maksimalan broj korisnika iako server nije uopšte bio opterećen. Maksimalan dozvoljeni broj korisnika je sada povećan tako da se ovaj problem više ne bi trebao dešavati.</p>

<p><b>25.2.2016 11:10</b> Predstavljamo vam <font color="#cfc">c9 v2.0</font> !!! Nove mogućnosti su:
<ol style="color:white"><li>Dodatno utegnute permisije na serveru.<br>&nbsp;</li>
<li>Umjesto OR plugina sada imamo plugin "Zadaci" koji podržava više predmeta, lijepo je organizovan u stablo tako da studenti ustvari mogu koristiti ovaj plugin umjesto normalnog stabla ("Workspace").<br>&nbsp;</li>
<li>Osposobljen je debugger i valgrind. Dva nova runnera se sada zovu samo C i C++ (po defaultu C++11) imaju mogućnost korištenja debug moda u kojem se program izvršava kroz gdb. Debug mod se (de)aktivira klikom na ikonu sa bubom lijevo od runnera.<br>
<img src="/static/images/content/debugger.png">&nbsp;</li>
<li>Kada je debugger isključen program se izvršava kroz valgrind. Za sada se izlaz valgrinda može vidjeti samo u hidden datoteci .valgrind.out<br>&nbsp;</li>
<li>Popravljen je bug sa gubljenjem user.settings tako da korisnici sada mogu (trajno) promijeniti neke korisničke postavke, između ostalog i temu. Ako imate ideje za nove teme pošaljite :)<br>&nbsp;</li>
<li>Reorganizovana je admin sekcija. Sada najprije birate predmet, pa grupe unutar predmeta. Kada izaberete predmet možete kreirati zadatke što ujedno priprema plugin "Zadaci" (dovoljno je da kreirate posljednji zadatak u tutorijalu i automatski će biti popunjeni svi ispred njega) i omogućuje da klikom na check ikonu kreirate testove. Možete vidjeti na Osnovama računarstva kako to otprilike izgleda.<br>&nbsp;</li>
<li>Sadržaj vaših radnih prostora je reorganizovan, sve što ste radili na predmetu Osnove računarstva možete pronaći u folderu OR a nove sadržaje vezane za Tehnike programiranja pronaći ćete u folderu TP.<br>
<img src="/static/images/content/organizacija-foldera.png"></li></ol></p>

<p><b>23.2.2016 18:45</b> Zbog ažuriranja servera c9 isti će biti nedostupan u srijedu 24. 2. u periodu 18:00-20:00. Ažuriranje će donijeti znatno poboljšanje funkcionalnosti o čemu možete saznati ovdje. Studentima savjetujemo da planiraju svoje obaveze u skladu s ovim. Izvinjavamo se zbog prekida.<p>
<p><b>26.1.2016 21:30</b> Danas od otprilike 14:20 došlo je do nekih poteškoća zbog kojih je bilo otežano prijavljivanje na c9 i kreiranje novih datoteka na serveru, koje su otklonjene. Zbog ovih hitnih radova server je bio nedostupan danas od 14:50 do 15:15. Izvinjavamo se zbog prekida.<p>
<p><b>3.1.2016 20:30</b> Urađeno je nekoliko intervencija na serveru koje bi trebale popraviti stabilnost i performanse. Između ostalog, korisnici sada neće biti automatski odjavljeni nakon 15 minuta neaktivnosti, nego će biti &quot;suspendovani&quot; što znači da ne zauzimaju serverske resurse, ali će po zahtjevu biti opet pokrenuti. Smanjen je i broj pojavljivanja &quot;Reconnecting&quot; prozora jer se server ne restartuje nakon svake izmjene. Molimo korisnike da obrate pažnju na eventualne probleme u radu i prijave ih.</p>
<p><b>1.1.2016 15:00</b> Napravljen je plugin koji omogućuje formatiranje C/C++, C# i Java koda koristeći astyle biblioteku. Može mu se pristupiti kroz meni Edit &gt; Code Formatting ili pritiskom na tipke Ctrl+Shift+B (čime se automatski prepoznaje programski jezik i koristi odgovarajući plugin). Također korisnici bi sada trebali vidjeti informativni dijalog u slučajevima krahiranja programa. Sretna Nova Godina!</p>
<p><b>31.12. 11:00</b> Sinoć iza 23h je server postao nedostupan zbog buga koji je doveo do unosa invalidnih podataka u konfiguraciju sistema. Server je osposobljen jutros oko 10:30 a bug je otklonjen tako da više ne bi trebalo dolaziti do te vrste problema.</p>
<p><b>12.12. 09:30</b> Proteklih 24 sata dolazilo je do povremenih problema sa kreiranjem novih projekata te kompajliranjem i testiranjem postojećih. U pitanju su ponovo problemi sa dostizanjem inode limita (što se dešavalo i 31.10. i par puta kasnije). Rješenje koje smo uveli tada pokazalo se kao neadekvatno. Zbog toga je započeta veća rekonstrukcija smještajnog prostora na serveru. Pokušaćemo da osiguramo studentima da normalno koriste c9 tokom ovih radova, ali može se očekivati povremeno zatvaranje servera na 15-20 minuta.</p>
<p><b>11.12. 22:30</b> Znatno je popravljena stabilnost login procedure, resursi koji se iz raznih razloga nisu uspjeli učitati se automatski ponovo učitavaju sve dok se ne otvori c9 okruženje, a korisnici mogu vidjeti progress bar tako da u slučaju zaglavljivanja (koje se sada više ne bi trebalo dešavati) mogu uraditi reload. I sama login stranica sada "zna" da li se korisnikov server startovao ili nije. U slučaju da učitavanje nikako ne počinje, preporučujemo korisniku da uradi logout.</p>
<p><b>11.12. 12:00</b> Servis c9 je bio nedostupan od 10.12 u 19:30 do 11.12. u 09:30 zbog okolnosti koje su van naše kontrole. Od administratora ETFa nismo dobili konkretan odgovor na pitanje šta se tačno desilo. Nadamo se da se ovo više neće dešavati.</p>
<p><b>28.11. 22:00</b> Proteklih dana je započet značajan refactoring funkcionalnosti u admin sekciji, ali zbog ispita ovo će sada morati da pričeka do daljnjeg.</p>
<p><b>12.11. 10:00</b> U admin sekciji se sada može vidjeti koliko puta je student testirao program i rezultati posljednjeg testiranja.</p>
<p><b>11.11. 09:00</b> Dodata je nova kartica Autotest koja omogućuje korisniku da testira svoj program koristeći buildservice (isti sistem koji se koristi za testiranje zadaća poslanih kroz Zamger).</p>
<p><img src="/static/images/content/autotest.png"></p>
<p><b>5.11. 21:00</b> Popravljen je bug u admin sekciji zbog koje je novembar bio sortiran prije oktobra, pa se dešavalo da se aktivnosti iz novembra niti ne vide (zbog limita na broj poruka u logu).</p>
<p><b>5.11. 17:00</b> Uočeno je da u situacijama velikog opterećenja servera niko od prijavljenih korisnika ne može raditi, što je još gore nije moguće ni odjaviti neaktivne korisnike kako bi se smanjilo opterećenje. Zbog toga uveden je adaptivni limit na broj korisnika koji se prilagođava trenutnom stanju na serveru, a ostale korisnike moli da sačekaju.</p>
<p><b>3.11. 15:00</b> Omogućeno je slanje zadaća kroz C9! Više informacija na courseware-u: <a href="http://c2.etf.unsa.ba/mod/resource/view.php?id=42584" style="color:cyan">http://c2.etf.unsa.ba/mod/resource/view.php?id=42584</a>.</p>
<p><b>1.11. 14:20</b> Primjećeno je da C9 ustvari ne dozvoljava brisanje datoteka niti foldera, odnosno vi ih možete prividno obrisati ali se oni nakon nekog vremena vrate. Ovaj problem je otklonjen. U situacijama kada greškom pobrišete neke datoteke, možete ih vratiti koristeći Changes karticu s lijeve strane koja memoriše sve što ste radili svakog dana, a ako vam treba nešto što ste napravili pa pobrisali unutar istog dana možete se obratiti tutoru.</p>
<p><b>31.10. 16:40</b> Od danas oko 14h desile su se neke poteškoće na serveru zbog kojih nije bilo moguće kreirati nove fajlove (editovanje postojećih je radilo). Nije radilo ni praćenje aktivnosti studenta. Problemi su sada otklonjeni, njihov uzrok je prepoznat te se nadamo da se to više neće dešavati.</p>
<p><b>29.10. 23:00</b> C9 sada izbacuje informativne dijaloge u slučajevima kada se program ne može kompajlirati, kada ulazi u beskonačnu petlju, te u situaciji kada ostavite pokrenut program u zasebnom tabu (što je nepotrebno zauzimalo serverske resurse). Popravljen je bug zbog kojeg se dešavalo da se izlaz programa ili poruke grešaka ne vide. Popravljeno nekoliko bugova u OR pluginu (poruke "nemoguće kreirati folder koji već postoji" i slično).</p>
<p><b>29.10. 14:00</b> Primijećeno je da se Firefox koji se nalazi u labu 0-02 uspori pa i prestane potpuno raditi ako korisnik ima mnogo tabova sa pokrenutim programima (otvoreni editori ne predstavljaju problem, samo runneri). Poruka koja se dobije je "The script on this page has stopped responding". Ovaj problem nije moguće riješiti jer su računari u labu jednostavno preslabi za takav način rada. Još jednom apelujemo na studente da zatvaraju tabove na kojima ne rade trenutno, što će se desiti automatski ako za otvaranje zadataka koriste OR plugin.</p>
<p><b>28.10. 21:00</b> Prilikom radova na serveru greškom su izbačeni svi korisnici na nekih 15-20 minuta. Izvinjavamo se zbog ovih okolnosti i nadamo se da se neće ponoviti.</p>
<p><b>28.10. 09:00</b> Server na kojem se nalazi C9 je dobio značajno memorijsko proširenje, pa bi sada sve skupa trebalo raditi mnogo bolje. Nadamo se da se neće više dešavati poteškoće sa pristupom koje su uočene proteklih dana a pogotovo preko vikenda.</p>
<p><b>27.10. 13:00</b> Prilikom sinoćnjih popravki na OR pluginu napravljena je greška zbog koje je Run dugme ponekada bilo disablovano (moralo se ići kroz meni Run > Run with... > C (simple) a kasnije kroz Run dugme na runneru).</p>
<p><b>27.10. 09:20</b> Nastavljaju se radovi na popravljanju performansi. Zbog greške u konfiguraciji nisu radili websockets nego je korišten polling. Otvaranje statistike grupe (u admin sekciji) je sada znatno brže i ne opterećuje server.</p>
<p><b>26.10. 23:00</b> Radi popravljanja performansi sada otvaranje zadatka kroz OR plugin zatvara sve ostale tabove. Ako to ne želite možete koristiti Workspace plugin za otvaranje podzadataka.</p>
<p><b>24.10. 15:20</b> Povremeno (vrlo rijetko) se dešavalo da se WebIDE otvori ali ne može učitati nijednu datoteku, pa ni spisak zadataka u OR pluginu. To se dešavalo svima i refresh/logout nije pomagao. Ovaj problem je sada otklonjen i mislimo da se više ne može dešavati.</p>
<p><b>23.10. 12:00</b> Popravljen problem sa povremenim neuspješnim učitavanjem spiska zadataka u OR pluginu. Dešavalo se da se zadaci nikada ne učitaju ili da se učitaju djelomično ili da budu loše sortirani.</p>
<p><b>22.10. 22:20</b> Omogućeno kompajliranje i pokretanje programa u folderima koji sadrže razmake (i druge neobične znakove) u imenu.</p>
<p><b>22.10. 22:00</b> Povećan memorijski limit za studentske programe. Sa starim limitom je bilo nemoguće pokretanje C++ programa nakon uključivanja iostream biblioteke, jer ona sama za sebe uzme popriličnu količinu memorije.</p>
<p><b>22.10. 20:00</b> Opcija regenerisanja statistike za čitavu grupu je sada isključena jer je ustanovljeno da previše opterećuje server.</p>
<p><b>22.10. 11:00</b> Kako bi se spriječilo da logiranje rada u IDE-u potroši sav dostupni diskovni prostor, uvedeno je procesiranje i brisanje logova svakog dana u ranim jutarnjim satima. To je zahtijevalo totalnu promjenu načina logiranja. &quot;Besplatno&quot; su studenti dobili vlastiti Git repozitorij kojem mogu pristupiti kroz karticu Changes (sa lijeve strane). Studenti mogu vidjeti sve promjene koje su pravili, komparirati stare datoteke sa novim, te vraćati na staru verziju. Commit se radi u ranim jutarnjim satima.</p>
<p><img src="/static/images/content/changes.png" width="999" height="584"></p>
<p><b>21.10. 19:00</b> Danas u toku dana je uočeno da se nekim studentima pokreće stara verzija programa ako je u programu bila kompajlerska greška. To je zahtijevalo prepravku runnera za C. Molim sve koji prijavljuju problem sa nedostajućom &quot;runme&quot; datotekom da probaju ponovo nakon ovih ispravki.</p>
<p><b>21.10. 11:30</b> Popravljen problem sa gubitkom sesije u admin sekciji na nekim preglednicima.</p>
<p><b>20.10. 19:00</b> U admin panelu dodana opcija regenerisanja statistike za čitavu grupu odjednom (umjesto za svakog studenta posebno).</p>
<p><b>20.10. 07:00</b> Dodana opcija pokretanja C++ programa po C++11 standardu.</p>
